# Generated by Django 2.2 on 2019-06-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('fl_active', models.BooleanField(default=False)),
                ('group', models.ManyToManyField(to='groups_app.GroupApp')),
            ],
        ),
    ]
