# Generated by Django 2.2 on 2019-04-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='group',
            field=models.ManyToManyField(to='groups_app.GroupApp'),
        ),
    ]
