# Generated by Django 2.2 on 2019-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0003_auto_20190404_1616'),
        ('users_app', '0002_auto_20190404_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='group',
        ),
        migrations.AddField(
            model_name='userapp',
            name='group',
            field=models.ManyToManyField(to='groups_app.GroupApp'),
        ),
    ]
