# Generated by Django 2.2 on 2019-04-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0005_auto_20190405_2302'),
        ('users_app', '0003_auto_20190405_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='group',
        ),
        migrations.AddField(
            model_name='userapp',
            name='group',
            field=models.ManyToManyField(to='groups_app.GroupApp'),
        ),
    ]
