# Generated by Django 2.2 on 2019-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0002_groupapp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupapp',
            name='user',
        ),
        migrations.AlterField(
            model_name='groupapp',
            name='fl_active',
            field=models.BooleanField(default=False),
        ),
    ]
