# Generated by Django 2.2 on 2019-04-06 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0001_initial'),
        ('groups_app', '0002_groupapp_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupapp',
            name='group',
        ),
        migrations.AddField(
            model_name='groupapp',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='routes_app.RouteApp'),
            preserve_default=False,
        ),
    ]
