# Generated by Django 2.2 on 2019-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0001_initial'),
        ('groups_app', '0003_auto_20190404_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapp',
            name='route',
            field=models.ManyToManyField(to='routes_app.RouteApp'),
        ),
    ]
