# Generated by Django 2.2 on 2019-04-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0003_auto_20190405_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupapp',
            old_name='group',
            new_name='route',
        ),
    ]
