# Generated by Django 2.2 on 2019-04-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes_app', '0001_initial'),
        ('groups_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRouteApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups_app.GroupApp')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routes_app.RouteApp')),
            ],
        ),
    ]
