# Generated by Django 2.2 on 2019-04-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups_routes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprouteapp',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups_app.GroupApp'),
        ),
    ]
