# Generated by Django 2.2 on 2019-06-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('authorization', models.CharField(choices=[('GET', 'LIST'), ('POST', 'ADD'), ('PUT', 'EDIT'), ('DELETE', 'DELETE')], max_length=6)),
                ('fl_active', models.BooleanField(default=False)),
            ],
        ),
    ]
